steps:
### Docker build
- id: 'docker-build'
  name: 'gcr.io/cloud-builders/docker'
  dir: './'
  args: ['build','-t','gcr.io/$PROJECT_ID/$_SERVICE_NAME:$BUILD_ID','.','-f','cicd/Dockerfile','-t','gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest']

### Docker push to registry
- id: 'docker-push-to-registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/$_SERVICE_NAME:$BUILD_ID']

### Deploy container image to Cloud Run
- id: 'deploy-to-cloud-run'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$_SERVICE_NAME', '--image', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$BUILD_ID', '--region', 'us-east1', '--platform', 'managed']

images: ['gcr.io/$PROJECT_ID/$_SERVICE_NAME:$BUILD_ID']